# バージョン
teleport_version: 3.0.1

# アーキテクチャ
teleport_architecture: linux-amd64

# エディション [enterprise/oss]
teleport_edition: enterprise

# インストール時の種別 [ node/auth/proxy/auth-proxy ]
teleport_type: ""

# エディションがenterprise時のライセンスファイルのパス
teleport_license: license.pem

# Teleportのデータディレクトリ
teleport_data_dir: /var/lib/teleport/

# typeがproxy時に指定するAuthサーバーのIPアドレス
teleport_auth_server_addr: ""

# typeがproxyもしくはauth-proxy時のdomain名
teleport_proxy_domain: ""

# authサーバー作成時にのteleportのクラスター名
teleport_cluster_name: ""

# リージョン
teleport_region: ap-northeast-1

# teleportで使用するS3のBucket名
teleport_bucket: ""

# teleportのサーバーにてLet's encrypt実行時に使用するEMmail
teleport_email: ""

# teleportで使用するDynamoDBのデーブル名
teleport_dynamodb_table: ""

# authサーバー作成時のteleportのバックエンドストレージ設定
teleport_storage:
    type: dynamodb
    region: "{{ teleport_region }}"
    table_name: "{{ teleport_dynamodb_table }}"
    audit_events_uri: "dynamodb://{{ teleport_dynamodb_table }}-events"
    audit_sessions_uri: "s3://{{ teleport_bucket }}/records"

# ノード用SSHポート
teleport_node_ssh_service_port: 3022

# Proxy用SSHポート
teleport_proxy_ssh_listen_port: 3023

# Proxy用tunnel待ち受けポート
teleport_proxy_tunnel_listen_port: 3024

# Auth用api待ち受けポート
teleport_auth_api_listen_port: 3025

# Proxy用WEB待ち受けポート
teleport_proxy_web_listen_port: 3080
