---
# -----------------------------------------------------------------------------
# Teleport設定
# -----------------------------------------------------------------------------
# バージョン
teleport_version: 3.0.1

# アーキテクチャ
teleport_architecture: linux-amd64

# エディション [enterprise/oss]
teleport_edition: enterprise

# インストール時の種別 [ node/auth/proxy/auth-proxy ]
teleport_type: ''

# エディションがenterprise時のライセンスファイルのパス
teleport_license: license.pem

# TeleportのModule Binaryのインストール先
teleport_bin_dir: /usr/local/bin/

# Teleportのデータディレクトリ
teleport_data_dir: /var/lib/teleport/

# typeがproxy時に指定するAuthサーバーのIPアドレス
teleport_auth_server_addr: ''

# typeがproxyもしくはauth-proxy時のdomain名
teleport_proxy_domain: ''

# authサーバー作成時のteleportのクラスター名
teleport_cluster_name: ''

teleport_region: ap-northeast-1

teleport_bucket: ''

teleport_email: ''

# teleportで使用するDynamoDBのデーブル名
teleport_dynamodb_table: ''

# authサーバー作成時のteleportのバックエンドストレージ設定
teleport_storage:
    type: dynamodb
    region: "{{ teleport_region }}"
    table_name: "{{ teleport_dynamodb_table }}"
    audit_events_uri: "dynamodb://{{ teleport_dynamodb_table }}-events"
    audit_sessions_uri: "s3://{{ teleport_bucket }}/records"

# ノード用SSHポート
teleport_node_ssh_service_port: 3022

# Proxy用SSHポート
teleport_proxy_ssh_listen_port: 3023

# Proxy用tunnel待ち受けポート
teleport_proxy_tunnel_listen_port: 3024

# Auth用api待ち受けポート
teleport_auth_api_listen_port: 3025

# Proxy用WEB待ち受けポート
teleport_proxy_web_listen_port: 3080




# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数
# -----------------------------------------------------------------------------
teleport_common:
    auth_token: /var/lib/teleport/token
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    storage: "{{ teleport_storage }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(auth用)
# -----------------------------------------------------------------------------
teleport_auth_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{ teleport_auth_api_listen_port }}"
    license_file: "{{ teleport_data_dir }}{{ teleport_license.split('/')[-1] }}"
    authentication:
        type: local
        second_factor: "off"
        u2f:
            app_id: "https://localhost:{{ teleport_proxy_web_listen_port }}"
            facets:
            - "https://localhost:{{ teleport_proxy_web_listen_port }}"
    cluster_name: "{{ teleport_cluster_name }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(proxy用)
# -----------------------------------------------------------------------------
teleport_proxy_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{ teleport_proxy_ssh_listen_port }}"
    tunnel_listen_addr: "0.0.0.0:{{ teleport_proxy_tunnel_listen_port }}"
    web_listen_addr: "0.0.0.0:{{ teleport_proxy_web_listen_port }}"
    public_addr: "{{ teleport_proxy_domain }}:443"
    https_cert_file: "{{ teleport_data_dir }}{{ teleport_certificate.split('/')[-1] }}"
    https_key_file: "{{ teleport_data_dir }}{{ teleport_private_key.split('/')[-1] }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(ssh用)
# -----------------------------------------------------------------------------
teleport_ssh_service:
    enabled: "no"
