- debug:
    msg: "Install Teleport token fetcher from SSM"

- template:
    src: templates/teleport-ssm-get-token.j2
    dest: "{{ teleport_bin_dir }}teleport-ssm-get-token"
    mode: "0755"
  become: yes
