teleport_common:
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    storage: "{{ teleport_storage }}"
    auth_servers:
        - "{{ teleport_auth_server_addr }}"

teleport_auth_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{ teleport_auth_api_listen_port }}"

    license_file: "{{ teleport_data_dir }}{{ teleport_license.split('/')[-1] }}"
    authentication:
        type: local
        second_factor: "off"
        u2f:
            app_id: "https://localhost:{{ teleport_proxy_web_listen_port }}"
            facets:
            - "https://localhost:{{ teleport_proxy_web_listen_port }}"
    cluster_name: "{{ teleport_cluster_name }}"

teleport_proxy_service:
    enabled: "no"

teleport_ssh_service:
    enabled: "yes"
