---
# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数
# -----------------------------------------------------------------------------
teleport_common:
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    storage: "{{ teleport_storage }}"
    auth_servers:
        - "{{ teleport_auth_server_addr }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(auth用)
# -----------------------------------------------------------------------------
teleport_auth_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{ teleport_auth_api_listen_port }}"
    license_file: "{{ teleport_data_dir }}{{ teleport_license.split('/')[-1] }}"

    authentication:
        type: local
        second_factor: "off"
        u2f:
            app_id: "https://localhost:{{ teleport_proxy_web_listen_port }}"
            facets:
            - "https://localhost:{{ teleport_proxy_web_listen_port }}"
    cluster_name: "{{ teleport_cluster_name }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(proxy用)
# -----------------------------------------------------------------------------
teleport_proxy_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{teleport_proxy_ssh_listen_port }}"
    tunnel_listen_addr: "0.0.0.0:{{ teleport_proxy_tunnel_listen_port }}"
    web_listen_addr: "0.0.0.0:{{ teleport_proxy_web_listen_port }}"
    public_addr: "{{ teleport_proxy_domain }}:443"
    https_cert_file: "{{ teleport_data_dir }}fullchain.pem"
    https_key_file: "{{ teleport_data_dir }}privkey.pem"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(ssh用)
# -----------------------------------------------------------------------------
teleport_ssh_service:
    enabled: "yes"
