---
# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数
# -----------------------------------------------------------------------------
teleport_common:
    auth_token: /var/lib/teleport/token
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    storage: "{{ teleport_storage }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(auth用)
# -----------------------------------------------------------------------------
teleport_auth_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3025
    license_file: "{{ teleport_data_dir }}{{ teleport_license.split('/')[-1] }}"

    authentication:
        type: local
        second_factor: "off"
    u2f:
        app_id: https://localhost:3080
        facets:
        - https://localhost:3080
    cluster_name: "{{ teleport_cluster_name }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(proxy用)
# -----------------------------------------------------------------------------
teleport_proxy_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3080
    web_listen_addr: 0.0.0.0:3080
    public_addr: "{{ teleport_proxy_domain }}:443"
    https_cert_file: "{{ teleport_data_dir }}{{ teleport_certificate.split('/')[-1] }}"
    https_key_file: "{{ teleport_data_dir }}{{ teleport_private_key.split('/')[-1] }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(ssh用)
# -----------------------------------------------------------------------------
teleport_ssh_service:
    enabled: "no"
