# バージョン
teleport_version: 3.0.1

# アーキテクチャ
teleport_architecture: linux-amd64

# エディション [enterprise/oss]
teleport_edition: enterprise

# インストール時の種別 [ node/auth/proxy/auth-proxy ]
teleport_type: ""

# エディションがenterprise時のライセンスファイルのパス
teleport_license: license.pem

# Teleportのデータディレクトリ
teleport_data_dir: /var/lib/teleport/

# typeがproxy時に指定するAuthサーバーのIPアドレス
teleport_auth_server_addr: ""

# typeがproxyもしくはauth-proxy時のdomain名
teleport_proxy_domain: teleport.example.com

# authサーバー作成時にのteleportのクラスター名
teleport_cluster_name: teleport.example.com

# リージョン
teleport_region: ap-northeast-1

# teleportで使用するS3のBucket名
teleport_bucket: teleport.example.com-certs

# teleportのサーバーにてLet's encrypt実行時に使用するEMmail
teleport_email: test@teleport.example.com

# teleportで使用するDynamoDBのデーブル名
teleport_dynamodb_table: teleport.example.com

# Proxy用tunnel待ち受けポート
teleport_proxy_tunnel_listen_port: 3080

