---
# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数
# -----------------------------------------------------------------------------
teleport_common:
    auth_token: "{{ teleport_data_dir }}token"
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    auth_servers:
        - "{{ teleport_auth_server_addr }}"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(auth用)
# -----------------------------------------------------------------------------
teleport_auth_service:
    enabled: "no"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(proxy用)
# -----------------------------------------------------------------------------
teleport_proxy_service:
    enabled: "no"

# -----------------------------------------------------------------------------
# teleportの設定ファイル用変数(ssh用)
# -----------------------------------------------------------------------------
teleport_ssh_service:
    enabled: "yes"
    listen_addr: "0.0.0.0:{{ teleport_node_ssh_service_port }}"
