teleport_common:
    auth_token: /var/lib/teleport/token
    nodename: "{{ ansible_fqdn }}"
    advertise_ip: "{{ ansible_default_ipv4.address }}"
    log:
        output: stderr
        severity: DEBUG
    data_dir: "{{ teleport_data_dir }}"
    auth_servers:
        - "{{ teleport_auth_server_addr }}"

teleport_auth_service:
    enabled: "no"

teleport_proxy_service:
    enabled: "yes"
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3080
    web_listen_addr: 0.0.0.0:3080
    public_addr: "{{ teleport_proxy_domain }}:443"
    https_cert_file: "{{ teleport_data_dir }}fullchain.pem"
    https_key_file: "{{ teleport_data_dir }}privkey.pem"

teleport_ssh_service:
    enabled: "no"
