---
  - hosts: "{{ host_name }}"
    vars_files:
        - vars/main.yaml
    pre_tasks:
        # パラメーター指定用プロンプト
        - include: prompt.yaml

        # teleport.yaml用パラメータの読み込み
        - include_vars: "vars/{{ teleport_type }}.yaml"

        # DynamoDB, S3, Route53のリソースチェック
        - include: check.yaml
          when: teleport_auth_service.enabled  == 'yes'

        - debug: msg="{{ teleport_auth_service }}"
        - debug: msg="{{ teleport_proxy_service }}"
    roles:
        - { role: teleport }
        - { role: teleport-ssm-publish-tokens, when: "teleport_auth_service.enabled  == 'yes'" }
        - { role: teleport-get-cert, when: "teleport_auth_service.enabled  == 'yes'" }
