dependencies:
  - { role: pip }
  - { role: urllib3, when: "ansible_python.version.major <= 2 and ansible_python.version.minor <= 7" }
  - { role: cryptography, when: "ansible_distribution == 'Ubuntu' and ansible_python.version.major <= 2" }
